# Generated by Django 5.0.6 on 2024-05-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisrtbook', '0005_logintable_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginTable',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
